---
services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - app-network

  lets-a-go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lets-a-go
    environment:
      - DOCKER=true
    volumes:
      - ./path/to/local/dir:/path/in/container
    ports:
      - "8080:8080" # Adjust the port mapping as needed
    restart: unless-stopped
    depends_on:
      - jackett
    networks:
      - app-network

networks:
  app-network:
    driver: bridge